version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: report-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - report-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  phonedirectory-api:
    build:
      context: .
      dockerfile: PhoneDirectory.API/Dockerfile
    container_name: phonedirectory-api
    ports:
      - "5001:8080"
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__DefaultConnection=Server=DESKTOP-KUS4Q12\\SQLEXPRESS;Database=PhoneDirectoryDb;Trusted_Connection=True;TrustServerCertificate=True;Integrated Security=True;
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - report-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  report-api:
    build:
      context: .
      dockerfile: Report.API/Dockerfile
    container_name: report-api
    ports:
      - "5003:8080"
      - "5004:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__DefaultConnection=Server=DESKTOP-KUS4Q12\\SQLEXPRESS;Database=Report;Trusted_Connection=True;TrustServerCertificate=True;Integrated Security=True;
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - report-network
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:

networks:
  report-network:
    driver: bridge