version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: report-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - report-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  report-api:
    build:
      context: .
      dockerfile: src/Report.API/Dockerfile
    container_name: report-api
    ports:
      - "5002:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - Services__PhoneDirectory=http://phonedirectory-api:5001
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - report-network

  phonedirectory-api:
    build:
      context: ../PhoneDirectory
      dockerfile: src/PhoneDirectory.API/Dockerfile
    container_name: phonedirectory-api
    ports:
      - "5001:5000"
    networks:
      - report-network

volumes:
  rabbitmq_data:

networks:
  report-network:
    driver: bridge
