services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq  
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    restart: always
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  phonedirectory.api:
    build:
      context: .
      dockerfile: Phonedirectory.API/Dockerfile
    container_name: phonedirectory-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5133
      - RabbitMQ__HostName=rabbitmq 
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=PhoneDirectory;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "5133:5133"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mssql:
        condition: service_healthy
    networks:
      - app_network

  report.api:
    build:
      context: .
      dockerfile: Report.API/Dockerfile
    container_name: report-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5191
      - RabbitMQ__HostName=rabbitmq 
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=Report;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "5191:5191"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mssql:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
